name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x gradlew
    
    - name: Start Application
      run: |
        java -jar ./artifacts/app-card-delivery.jar --server.port=8080 &
        sleep 10
    
    - name: Run tests
      run: ./gradlew test -Dselenide.headless=true
